# Generated by Django 4.1.7 on 2023-03-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_user_task_description_task_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
