# Generated by Django 4.1.7 on 2023-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_category_alter_task_assigned_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default='empty category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, null=True),
        ),
    ]
