# Generated by Django 4.1.7 on 2023-03-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_category_alter_task_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='empty title', max_length=100, null=True),
        ),
    ]
